"""WebSocket event type definitions."""

# Server → Client events
APPOINTMENT_STATUS_CHANGED = "APPOINTMENT_STATUS_CHANGED"
DOCK_STATUS_CHANGED = "DOCK_STATUS_CHANGED"
SLOT_LOCKED = "SLOT_LOCKED"
SLOT_RELEASED = "SLOT_RELEASED"

# Client → Server events (drag-and-drop)
DRAG_START = "DRAG_START"
DRAG_END = "DRAG_END"
DRAG_COMMIT = "DRAG_COMMIT"
